### ISSUE TITLE
Não está instalando...

### ISSUE THREAD

**Issue by hosios** [LibreMacro/Library#1]
**PC**
Uso Linux Mint 20.2 x86_64, Kernel: 5.4.0-88-generic, Cinnamon, NVIDIA GeForce GT 440

**LibreOffice**
Version: 7.2.1.2 / LibreOffice Community
Build ID: 20(Build:2)
CPU threads: 4; OS: Linux 5.4; UI render: default; VCL: gtk3
Locale: es-PY (en_US.UTF-8); UI: pt-BR
Ubuntu package version: 1:7.2.1~rc2-0ubuntu0.20.04.1~lo3
Calc: threaded

Ao tentar instalar a extensão, recebo a seguinte mensagem de erro: (veja imagem - infelizmente não dá pra copiar o texto do erro)
[Link pra Imagem](https://nextcloud.paulgjanzen.com/index.php/s/g2nGkXLTHyaDpeF)

**Comment by marcoscesteves** [comment]
Estamos iniciando a acompanhar o que ocorreu em seu caso. Dúvida: este tipo de problema ocorre somente quando instala a nossa extensão ou já ocorreu com outras? Poderia testar com outras e, em seguida, nos dar um retorno ?

**Comment by hosios** [comment]
Eu acabei de instalar a extensão [Numbertext](https://extensions.libreoffice.org/en/extensions/show/numbertext-1) e funcionou sem problemas. 
Tentei instalar a LibreMacro diretamente abrindo o arquivo, e também tentei instalar dentro da janela de extensões com o mesmo erro.

**Comment by hosios** [comment]
Acabei de instalar a nova versão da LibreMacro (v010.oxt) e essa instalou, assim que as alterações que vocês fizeram solucionaram o problema.

**Comment by marcoscesteves** [comment]
Olá. Hosios. Primeiramente, agradeço o seu feedback. Vou considerar então esta demanda resolvida. 

Caso o problema ocorra em versões futuras, agradeço se puder nos comunicar. Um abraço.
